name: "Django deploy workflow"

on:
  push:
    branches: [ master ]

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:14.6
        env:
          POSTGRES_DB: enimi_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
    
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_TOKEN }}
          known_hosts: 'any_host'
      - name: test and pull repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_TOKEN }}
          port: 22
          script: |
            cd enimi
            git pull
            docker-compose down
            docker-compose up -d
            docker ps
            exit
